### PR TITLE
OUR-321: Fixed Since the redesign the number of posts I have made on …

### PR DESCRIPTION
**Pull request by Aaen**
Since the redesign the number of posts I have made on the forum is not visible anymore
Not even on my own profile page.

### CODE REVIEW

**Comment by dawoe** [comment]
Hey Dennis,

Thx for the fix. Only reason I wanted this back, is to see how many posts I have to make to catch up with you :-)

**Comment by Aaen** [comment]
Okay Dave :)

**Comment by nul800sebastiaan** [comment]
Not sure why it doesn't show as merged but I just merged this one so closing it manually then!

**Comment by nul800sebastiaan** [comment]
Duh.. I did it wrong, that's why! Sorry :-) But all merged in now.

**Pull request closed without merging**
