### PR TITLE
Added footer link to the Terms of Conditions

### PR DESCRIPTION
**Pull request by abjerner**
As suggested by Niels here: https://our.umbraco.org/forum/using-umbraco-and-getting-started/89827-impact-of-slack-community-on-these-forums-and-on-the-umbraco-community-in-general#comment-283642

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Terms *of* service ! 😉

**Comment by nul800sebastiaan** [comment]
Or, Terms **and** conditions I guess is what we called it.

**Comment by abjerner** [comment]
Bah. Seems I was a bit too quick. I've made another commit so it's now called **Terms and Conditions** as the page ;)

And yes, I think a page like that is normally called Terms of Service rather than Terms and Conditions.

**Comment by nul800sebastiaan** [comment]
Thanks mate, some better pages for this are in the works and we can link them up when they're done (in the next few weeks). I'll close this one.

**Pull request closed without merging**
