### PR TITLE
Highlight selected docs version

### PR DESCRIPTION
**Pull request by greystate**
This is a first attempt to address [UmbracoDocs #1665](https://github.com/umbraco/UmbracoDocs/issues/1665).

Since I don't have a way to build the site and test, this is just a draft PR for anyone to comment on and discuss, since I don't know if this will be "enough" - @jmayntzhusen [seemed to imply](https://github.com/umbraco/UmbracoDocs/issues/1665#issuecomment-481580006) that there was more to it than the changes included in this draft PR.

fixes https://github.com/umbraco/UmbracoDocs/issues/1665

### CODE REVIEW

**Comment by abjerner** [comment]
@greystate Awesome. I think you're on the right track. Currently it looks like this:

image

**Comment by greystate** [comment]
Oh nice - thanks @abjerner ! Looks right :-)

**Comment by jmayntzhusen** [comment]
This is great @greystate , with my bit of work I was mostly talking if we wanted to remove the `(current)` as well, but that is not necessary here, and also turns out it is not that much work 😄

Anyways I think this looks nice and would be helpful in making it clearer what version we are on!

**Comment by dampee** [comment]
I would not hestitate to merge this in.  Let's ping @nul800sebastiaan :-)

**Comment by nul800sebastiaan** [comment]
Sweet, thanks very much!

**Pull request merged**
