### PR TITLE
Add piotrbach.com blog to RSS feed

### PR DESCRIPTION
**Pull request by piotrbach**

### CODE REVIEW

**Review by abjerner — CHANGES_REQUESTED** [review]
Hi @piotrbach 

It appears that the `<item>` elements in your feed each are missing a `<link>` element with the URL to the corresponding blog post.

If you add this, I think the PR should be good to merge 😉

**Comment by piotrbach** [comment]
Hi @abjerner ! Oh, I missed that 😊. Just updated the feed, let's try one more time ;p

**Review by abjerner — APPROVED** [review]
Great 😃 

It should be good to merge now I think. I don't have merge rights, so we'll need someone from HQ to merge it in 😉

**Comment by piotrbach** [comment]
Big thanks @abjerner 🔥🚀 and have a great weekend! 🤝

**Comment by nul800sebastiaan** [comment]
Well let's see how it goes then! 🚀

**Comment by nul800sebastiaan** [comment]
Thanks @piotrbach - it seems to have worked! The [blogs page ](https://community.umbraco.com/learn-about-the-community/blog-posts/) is cached and I'm not sure for how long but soon your posts will start appearing  

Thanks for your contribution and blog posts, and congrats on a new contributor badge on your Our profile! https://our.umbraco.com/members/id:155740/ 🎖️

**Comment by piotrbach** [comment]
Hi, big thanks @nul800sebastiaan @abjerner, everything works! 💚
Have a great day!

**Pull request merged**
