### PR TITLE
Added my blog

### PR DESCRIPTION
**Pull request by RachBreeze**
Hello

I have added the RSS feed for my blog to the list as per https://twitter.com/mattbrailsford/status/1706373877268365801

Many thanks for developing this functionality

#H5YR 

Rachel

### CODE REVIEW

**Comment by abjerner** [comment]
Hi @RachBreeze 

I just had a look at your feed, and the dates are not RFC 822 as required by the RSS specification:

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.rachelbreeze.dev%2Fblogs%2Frss.xml

At best, this causes some ambiguity about the time (as your format doesn't specify whether it's UTC or something else). At worst, various RSS readers may fail to correctly parse the date and thus fail.

From what I can tell, the old RSS implementation on Our Umbraco would actually accept your format, but would consider the time as UTC - although it should probably be parsed as UTC +1 as UK is still observering summer time (right?). So while the dates are not entirely correct, this shouldn't be a big deal.

I don't think the newer implementation on [community.umbraco.com](https://community.umbraco.com/learn-about-the-community/blog-posts/) is open source, so I can't tell for sure whether this implementation will accept your format. Maybe it will work the same as the old Our implementation - or maybe it will fail to parse your feed. Maybe someone on Our could help shed some light on this?

**Review by nul800sebastiaan — CHANGES_REQUESTED** [review]
More importantly: the link is being generated incorrectly, it ends up as `https://www.rachelbreeze.dev/blogs/rss.xml/blogs/2-weeks-in-umbraco-accessibility-and-ai/",` (note the first `blogs/rss.xml/` part). 

Once you can fix your links I'll be happy to merge, of course fixing the dates would be nice too, but indeed not too big of a problem at the moment!

**Comment by RachBreeze** [comment]
Thank you, I've fixed the links, I will take a look at the date format tonight

**Comment by RachBreeze** [comment]
Hi @nul800sebastiaan  and @abjerner 

I just wanted to say thank you for your feedback. I've resolved those issues on the feed now.

#H5YR

**Comment by abjerner** [comment]
Looks good to me. And W3C is happy as well 👍 

image

**Review by nul800sebastiaan — APPROVED** [review]

**Comment by nul800sebastiaan** [comment]
Thanks @RachBreeze , merging and deploying now!

**Pull request merged**
