### PR TITLE
Updating list of HQ Github users

### PR DESCRIPTION
**Pull request by callumbwhyte**
The list of HQ Github users, which is used to exclude HQ from stats and automatic notifications, was rather out of date...

This change adds all missing D-Team, SWAT and COMA users in the organisation:

- daniellacl
- double-em
- filipbech
- jesperlange
- kenniholm
- kjsguld
- larsskjoldiversen
- mbentancour
- mmacoma
- mta-umbraco
- nikolajlauridsen
- RyuLindow
- thejokerd3
- trinenisse
- UmbraGreen-19
- UnicornSez

It would be nice to see former HQ-ers to keep contributing back and those contributions to be counted! Therefore this PR also removes any former HQ-ers that haven't contributed in the past 12 months:

- emilwangaa
- JAndrewBarta
- KennethJakobsen
- KristinaTheStoryteller
- madsrasmussen
- negyven6
- NicolaiOksen
- nielsthedane
- pedr0206
- perploug
- simonbusborg
- SuperJoachim
- zpqrtbnk

For some reason part of the list was duplicated in [2d986f452c](https://github.com/callumbwhyte/OurUmbraco/commit/2d986f452cc69189debf34a60d0dee5686ca4409) so I've removed that too.

Hopefully I didn't miss anyone...!

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @callumbwhyte - much has changed since then again, yikes! I'll close this one. 

We should automate this differently and "just" get the list from the groups on GitHub, but for now it's manual.. 😬 

I've updated the list for now, thanks for spending the time on this, helped me remember that we actually have lists in the GitHub teams already 👍

**Comment by callumbwhyte** [comment]
Indeed it has! Thanks for updating, and for the [spoiler](https://github.com/umbraco/OurUmbraco/blob/main/OurUmbraco.Site/config/githubhq.txt#L3) 😉

There's definitely a case for automating this somehow...

**Comment by nul800sebastiaan** [comment]
Glad you missed the other spoiler 😂

**Comment by callumbwhyte** [comment]
I saw it, can't link to more than 1 row ;-) There's a few in there, with some leavers too :(

**Pull request closed without merging**
