### PR TITLE
Package stats

### PR DESCRIPTION
**Pull request by jmayntzhusen**
@nul800sebastiaan 

This implementation is not caching the db calls - it does 3 calls per page hit and the page is only for hq. Should it be cached?

I also left in the old GetPackageStatisticsData() method, but am not using it - should it just be removed? 🙂

### CODE REVIEW

**Comment by hartviglarsen** [comment]
Is this for public or "internal" use? In case of the latter I don't see any harm in it not being cached. We're not going to be looking at it 25 times per day. 🙂

**Comment by jmayntzhusen** [comment]
This is supposed to be an internal page for now, where we can expand upon what we track.

If stats are deemed relevant for other things (fx a top x most downloaded packages past month could make sense in the package overview) we will consider doing it differently for that later.

**Comment by nul800sebastiaan** [comment]
> I also left in the old GetPackageStatisticsData() method, but am not using it - should it just be removed? 🙂

Yep just remove it.

Depending on how fast the queries return now you might want to consider caching. I suspect you won't need it for now though.

**Comment by jmayntzhusen** [comment]
Alright I cleaned it up for now 🙂

**Pull request merged**
