### PR TITLE
Aaron sadler uk add my blog

### PR DESCRIPTION
**Pull request by AaronSadlerUK**
Added my blog rss feed =]

### CODE REVIEW

**Comment by abjerner** [comment]
Hi @AaronSadlerUK,

I just had a look at your RSS feed. Unfortunately the parser on Our will ignore your posts as each `<item>` is missing the `pubDate` element. Could you add the `pubDate` element with a valid RFC 822 date? Then it should be good to merge 😉

**Comment by AaronSadlerUK** [comment]
Sure thing :)

**Comment by AaronSadlerUK** [comment]
That's updated.
Thanks!

**Comment by abjerner** [comment]
Great - seems to do the trick 😉

**Comment by nul800sebastiaan** [comment]
Thanks @AaronSadlerUK  - your blog posts will appear on the site soon!

**Comment by nul800sebastiaan** [comment]
@AaronSadlerUK 1b7d7f1632315f08e414078527eedf518e1ba7d0 - weird! 

I'll rename it back 😂

**Pull request merged**
