### PR TITLE
Update documentation icons

### PR DESCRIPTION
**Pull request by erikjanwestendorp**
Update the documentation icons so that they are more in line with the [documentation page](https://our.umbraco.com/documentation/).

### CODE REVIEW

**Comment by LottePitcher** [comment]
Hey @erikjanwestendorp, good spot that the icons need changing here too! Especially as those icons appear at the top of the Our home page if the user isn't logged in.

I tested your PR and the icons display at their natural size (1080px) as it seems there isn't any css restricting their width.

Inspecting https://our.umbraco.com/documentation/ the width is set inline:

`` and ``

so perhaps that's the easiest resolution for this partial too?

**Comment by erikjanwestendorp** [comment]
@LottePitcher Thanks for you review. Sorry I didn't pay attention to the size 😨. I just updated the PR!

**Comment by nul800sebastiaan** [comment]
Looks good now, thanks @erikjanwestendorp! 👍

**Comment by erikjanwestendorp** [comment]
@nul800sebastiaan Still a small issue (sorry my bad) created a new [PR](https://github.com/umbraco/OurUmbraco/pull/718)

**Pull request merged**
