### PR TITLE
OUR-230 GitHub web hook

### PR DESCRIPTION
**Pull request by warrenbuckley**
This Pull Request creates a GitHub WebHook endpoint so that members can be awarded karma & assigned the Core Contributor badge automagically every time a PR is merged back into the core of the repo.

Two appSettings need to be added to the web.config as follows:

``` XML
<!-- Karma for accepted & merged PR on GitHub -->
<add key="gitHubPullRequestKarma" value="50" />
<add key="gitHubWebHookSecret" value="superSecret" />
```

I will post a YouTube video of this in action, when it finally uploads showing it in action which may make this easier to review & understand what I did.

### CODE REVIEW

**Comment by warrenbuckley** [comment]
Said YouTube Video with this in action
https://www.youtube.com/watch?v=CZCjeBTSw50

**Comment by warrenbuckley** [comment]
@nul800sebastiaan when your back or whoever looks at this for reviewing. I just thought this would work with any of the Umbraco repos. So Documentation, new Identity as long as the WebHook setup & all use the same key. The community will be awarded greatly for accepted PR's.

It depends if we need an audit trail of what PR karma was assigned and from what repo & finally if different repo's would have different badges (member groups). Example 'Documentor' or something similar for PR accepted into docs repo or all contributions just use/share the same badge.

**Comment by warrenbuckley** [comment]
Any news on this at all @nul800sebastiaan ?

**Comment by nul800sebastiaan** [comment]
You'd be the FIRST one to know my friend. :-)

**Comment by warrenbuckley** [comment]
OK was not sure if its bacuse you guys busy/summer time vacations, its under review or been rejected :wink:

**Comment by warrenbuckley** [comment]
@nul800sebastiaan will you only consider this if I do an upstream fetch & rebase against your stuff to resolve merge conflicts (most likely csproj's or similar) or would you do this?

**Comment by nul800sebastiaan** [comment]
WARREN! Patience.

**Comment by warrenbuckley** [comment]
hahah you :heart: me really :stuck_out_tongue: 
OK I will go back to nagging you once every other week then :wink;

**Comment by nul800sebastiaan** [comment]
Have a few :beers: in the mean time ;-)

**Comment by warrenbuckley** [comment]
@nul800sebastiaan Refetched upstream & rebased. SLN builds out find after my merge conflicts with CSProj's.

**Comment by warrenbuckley** [comment]
Hey @nul800sebastiaan can you please tell me if this is going to be accepted or not.
If it is not can we close this please, as this has been open for a month & a half

**Comment by nul800sebastiaan** [comment]
Still haven't looked at it @warrenbuckley you know I've been super busy fixing urgent problems first mate. I still like the idea very much and will get to it when I can get to it. :-)

**Comment by warrenbuckley** [comment]
OK @nul800sebastiaan understandable. I know its not a quick thing to merge in (as a few moving parts) just a little demoralising for someone that it has been open so long, but understand there are more important things to do & with limited resources available to look at this kind of stuff.

Will go back to waiting patiently & if any questions at all with it let me know please :smile:

**Comment by nul800sebastiaan** [comment]
Frustrating for both you and me, wish we didn't have those horrible spammers or you know.. actual work to do ;-)

**Comment by nul800sebastiaan** [comment]
Hey Warren, sorry for not getting back to you for about 3 years :-o

I've apologized to you already in private, but we're taking a different route with the GitHub integration so I'll close this one.

**Comment by warrenbuckley** [comment]
@nul800sebastiaan I'm secretly crying inside now :-P

**Pull request closed without merging**
