### PR TITLE
Version compare

### PR DESCRIPTION
**Pull request by readingdancer**
I have cleaned up the markup so it's using bootstrap to better format on Mobile, I have also renamed the " Documenation" folder in the solution to the correct spelling: " Documentation "

I also added a couple of checks for Null values that I noticed could have caused exceptions ( as advised by Resharper )

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
I've refactored a lot of ReleaseDropdown.cshtml to remove unneccessary code and pulled in your changes to the styling manually. I appreciate the fixes to the wrongly spelled documentation views but you should open a new pull request for those.

To have multiple pull requests open at the same time, you can create a seperate branche for each "group of changes" (so for styling updates: create a branche, for moving the views to a new folder: create a branche).

**Comment by nul800sebastiaan** [comment]
Changes are here: https://github.com/umbraco/OurUmbraco/commit/aaccdbb1a43892197db882f8c9cc02ef5f84dba0?w=1

**Comment by nul800sebastiaan** [comment]
The default compare is now the previous version vs. the current version. This is also the default if you make an invalid selection, which then adds an error message.

https://our.umbraco.org/contribute/releases/compare - default
https://our.umbraco.org/contribute/releases/compare?from=7.4.3&to=7.2.8 - default with error

**Comment by readingdancer** [comment]
Hi,
Something seems to have broken, on my iPhone the layout if fine but I can't click on the dropdowns at all :(
Chris

**Comment by nul800sebastiaan** [comment]
I guess you didn't test your changes on iPhone before submitting them? :-)

**Pull request closed without merging**
