### PR TITLE
Update to Blog url and media location

### PR DESCRIPTION
**Pull request by OwainWilliams**
Just updating the config with new details of my blog and media location for the RSS feed.

### CODE REVIEW

**Comment by abjerner** [comment]
Congrats with your new blog @OwainWilliams 👍 

While your RSS feed is technically valid, the blog integration on Our would ignore your posts as they don't have a publication date, and they'll therefore don't really fit in with the blog list as it's sorted by date:

https://github.com/umbraco/OurUmbraco/blob/main/OurUmbraco/Community/BlogPosts/BlogPostsService.cs#L102

RSS dates should be specified using RFC 822, which can be a little tricky to get right, but the example below should do the trick (assuming `timestamp` is either `DateTime` or `DateTimeOffset`):

```csharp
timestamp.ToString("ddd, dd MMM yyyy HH:mm:ss", CultureInfo.InvariantCulture) + " " + timestamp.ToString("zzzz", CultureInfo.InvariantCulture).Replace(":", "");
```

Hope that helps 😉

**Comment by AaronSadlerUK** [comment]
I've used the microsoft syndication package for mine, it does all the formatting hard work for you 😉:

https://gist.github.com/AaronSadlerUK/465f490481153f73af8696210881afe2

```using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.ServiceModel.Syndication;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using Umbraco.Core;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.Web.Models;
using Umbraco.Web.Mvc;

    public class RSSController : RenderMvcController
    {
        [OutputCache(Duration = 1200)]
        public ActionResult Rss(ContentModel model)
        {
            var feed = GetFeedBase(
                model.Content.Url(null, UrlMode.Absolute),
                model.Content.Value<string>(Consts.Feeds.Title),
                model.Content.Value<string>(Consts.Feeds.Description),
                model.Content.Value<string>(Consts.Feeds.Copyright));
            var settings = XmlWriterSettings();

            using (var stream = new MemoryStream())
            {
                using (var xmlWriter = XmlWriter.Create(stream, settings))
                {
                    var rssFormatter = new Rss20FeedFormatter(feed, false);
                    rssFormatter.WriteTo(xmlWriter);
                    xmlWriter.Flush();
                }
                return File(stream.ToArray(), "application/rss+xml; charset=utf-8");
            }
        }

        [OutputCache(Duration = 1200)]
        public ActionResult Atom(ContentModel model)
        {
            var feed = GetFeedBase(
                model.Content.Url(null, UrlMode.Absolute), 
                model.Content.Value<string>(Consts.Feeds.Title), 
                model.Content.Value<string>(Consts.Feeds.Description),
                model.Content.Value<string>(Consts.Feeds.Copyright));
            var settings = XmlWriterSettings();

            using (var stream = new MemoryStream())
            {
                using (var xmlWriter = XmlWriter.Create(stream, settings))
                {
                    var rssFormatter = new Atom10FeedFormatter(feed);
                    rssFormatter.WriteTo(xmlWriter);
                    xmlWriter.Flush();
                }
                return File(stream.ToArray(), "application/atom+xml; charset=utf-8");
            }
        }

        private static XmlWriterSettings XmlWriterSettings()
        {
            var settings = new XmlWriterSettings
            {
                Encoding = Encoding.UTF8,
                NewLineHandling = NewLineHandling.Entitize,
                NewLineOnAttributes = true,
                Indent = true
            };

            return settings;
        }

        private SyndicationFeed GetFeedBase(string contentUrl, string title, string description, string copyright)
        {
            var hostname = Request.Url.AbsoluteUri;
            var feed = new SyndicationFeed(title,
                description, new Uri(hostname), contentUrl, DateTime.Now)
            {
                Copyright = new TextSyndicationContent($"{DateTime.Now.Year} {copyright}"),
                Items = GetBlogPosts()
            };

            return feed;
        }

        private IEnumerable<SyndicationItem> GetBlogPosts()
        {
            var items = new List<SyndicationItem>();
            var postings = UmbracoContext.Content.GetAtRoot().DescendantsOrSelfOfType("blogPost").OrderByDescending(x => x.CreateDate).Where(x => x.IsPublished() && x.IsVisible());
            foreach (var item in postings)
            {
                var postUrl = item.Url(null, UrlMode.Absolute);
                var title = item.Value<string>(Consts.Post.Title);
                var description = !string.IsNullOrEmpty(item.Value<string>(Consts.Post.Summary)) ?
                    item.Value<string>(Consts.Post.Summary) :
                    item.Value<HtmlString>(Consts.Post.PostBody).ToString().StripHtml().Truncate(200);

                items.Add(new SyndicationItem(title, description, new Uri(postUrl), item.Key.ToString(), item.CreateDate));
            }

            return items;
        }
    }
```

**Comment by OwainWilliams** [comment]
@abjerner ah, thanks. I'll fix that. 
@AaronSadlerUK ha! That could have saved me a day yesterday trying to build my own feed. I'll check it out though as it looks much more detailed than what I have done. Thanks! #h5yr

**Comment by abjerner** [comment]
Since we're talking alternatives, this is what I'm using for my blog:

```csharp
@inherits UmbracoViewPage<Bjerner.Website.Model.BjernerDk.BjernerDkRss>
@using System.Xml.Linq
@using Bjerner.Website.Extensions
@using Skybrud.Umbraco.RssUtils
@{
    Layout = null;

    // Get the root node of the blog
    IPublishedContent blog = Umbraco.TypedContent(1051);

    // Sort the blog posts and take the first 30
    IEnumerable<IPublishedContent> blogPosts = blog.Children.Where(x => x.DocumentTypeAlias == "BjernerDkBlogPost").OrderByDescending(x => x.CreateDate).Take(Model.RssLimit);

    // Initialize a new feed and add the blog posts
    RssFeed feed = new RssFeed(Model.RssTitle, "http://www.bjerner.dk/", blogPosts, delegate(IPublishedContent content) {
        return new RssItem {
            Title = content.Name,
            Link = content.UrlWithDomain(),
            PubDate = content.GetPublishDateUTC(),
            Guid = ("post" + content.Id)
        };
    });

    // Write the RSS feed to the response stream
    feed.Write(SaveOptions.None);

}
```

I'm using my [Skybrud.Umbraco.RssUtils](https://github.com/abjerner/Skybrud.Umbraco.RssUtils), however it is currently only available for Umbraco 7. Guess I need to update that 🤔 shouldn't require much, so maybe I'll have a new release tonight 😉 

I also wrote this article back in 2014 (for Umbraco 7.0.x): http://www.bjerner.dk/blog/creating-rss-feeds-with-umbraco/

IIRC, some of Microsoft old RSS logic has problems with generating correct RFC 822 dates. I think it's safe to use for UTC (Zulu time as for @AaronSadlerUK's blog), but fails with other time zones.

**Comment by abjerner** [comment]
Going slightly off topic, but if it helps anything, I've pushed a new beta release for Umbraco 8: https://www.nuget.org/packages/Skybrud.Umbraco.RssUtils/2.0.0-beta001

Snippet only needed to be adjusted a bit to work with Umbraco 8:

```cshtml
@inherits UmbracoViewPage<Bjerner.Website.Model.BjernerDk.BjernerDkRss>
@using System.Xml.Linq
@using Skybrud.Umbraco.RssUtils
@{
    Layout = null;

    // Get the root node of the blog
    IPublishedContent blog = Umbraco.Content(1051);

    // Sort the blog posts and take the first 30
    IEnumerable<IPublishedContent> blogPosts = blog.Children.Where(x => x.ContentType.Alias == "BjernerDkBlogPost").OrderByDescending(x => x.CreateDate).Take(Model.RssLimit);

    // Initialize a new feed and add the blog posts
    RssFeed feed = new RssFeed(Model.RssTitle, "http://www.bjerner.dk/", blogPosts, delegate(IPublishedContent content) {
        return new RssItem {
            Title = content.Name,
            Link = content.Url(mode: UrlMode.Absolute),
            PubDate = content.CreateDate.ToUniversalTime(),
            Guid = ("post" + content.Id)
        };
    });

    // Write the RSS feed to the response stream
    feed.Write(SaveOptions.None);

}
```

**Comment by AaronSadlerUK** [comment]
@abjerner Looks like Microsoft have documented an extension to fill the whole caused by the date time issue:

https://docs.microsoft.com/en-us/troubleshoot/dotnet/framework/rss20feedformatter-throw-exception

**Comment by OwainWilliams** [comment]
This has now been updated and fixed. I used the beta from @abjerner 👍 Thanks.
Super easy to use and only needed a small bit of tweaking for my site. 

Hopefully this will now make the RSS work for Our.

**Comment by abjerner** [comment]
@OwainWilliams great to hear you found a solution 👍 I think the feed looks alright now. I don't have merge rights for this repo, so we'll need to wait for someone from HQ to merge it in.

@AaronSadlerUK probably mostly for parsing, RFC 822 dates still have a lot of different combinations that you may need to handle. The blog implementation for Our uses my [Skybrud.Essentials](https://github.com/skybrud/Skybrud.Essentials). In particular, try having a look at this file:

https://github.com/skybrud/Skybrud.Essentials/blob/master/src/Skybrud.Essentials/Time/TimeUtils.Rfc822.cs

**Comment by nul800sebastiaan** [comment]
Sorry for the delay @OwainWilliams - this is all good indeed! 👍 Will roll out later today :)

**Pull request merged**
