### PR TITLE
fix(sidebar): fix height issue

### LINKED ISSUE #492: Sidebar height issue
Sometimes, there will be a situation, when height of sidebar lvl is greater, that allowed css value.
That will be the reason of such issue:

Selection_040

In this case, Mapping, Scheduling and Using Ioc are not available

### PR DESCRIPTION
**Pull request by daniloff200**
That should fix #492

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Hey there @daniloff200 - that's a lovely fix and it works as expected! 

Congrats on your first contribution to Our Umbraco, well done! 👍 

Do you have a profile on our.umbraco.com? I would love to give you a contributor badge!

**Comment by daniloff200** [comment]
hey @nul800sebastiaan 
Yeah, the same ID as here : daniloff200 :)

**Comment by nul800sebastiaan** [comment]
Wonderful, thanks again, you now have that shiny contrib badge, keep up the good work! https://our.umbraco.com/members/daniloff200/

FYI: The fix will roll out to live today.

**Comment by nul800sebastiaan** [comment]
Hi there @daniloff200,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Pull request merged**
