### PR TITLE
Dashboard filters

### PR DESCRIPTION
**Pull request by dawoe**
Added a filter for switching between issues and pull request. And option to filter on repository

### CODE REVIEW

**Comment by dawoe** [comment]
Better be held off. I know @abjerner is working on something similar using Examine. But it if it would really benefit maybe @cultiv can merge it for now

**Comment by abjerner** [comment]
I haven't tested the code, but I don't see any problem in merging this, as we can then benefit from it immediately.

The stuff I was working on may replace the current dashboard, but as I'm a bit caught up with work, I'm not sure when I can have something to deploy.

**Comment by dawoe** [comment]
@abjerner do you have the code you are working on somewhere ?

Dave

**Comment by nul800sebastiaan** [comment]
Cool, this is great for now, thanks @dawoe !

**Pull request merged**
