### PR TITLE
611 Cannot publish package if I don't enter the full NuGet URL

### PR DESCRIPTION
**Pull request by AaronSadlerUK**
Added regex model validation to check if the entered string contains nuget.org

Fixes: #611

### CODE REVIEW

**Comment by AaronSadlerUK** [comment]
@nul800sebastiaan If I delete and resubmit this, can it be included in hacktober 😂

**Comment by nul800sebastiaan** [comment]
Yes, it would count for the hacktoberfest `spam` list! 😛

**Comment by AaronSadlerUK** [comment]
I wont do that then 🤣

**Comment by nul800sebastiaan** [comment]
Works like a charm! Will release soon.

**Pull request merged**
