### PR TITLE
Add MCB blog

### PR DESCRIPTION
**Pull request by bjarnef**
Adding our blog at MCB where we once in a while blog about Umbraco related topics.
https://blog.mcb.dk/en/tag/umbraco

Not sure if the id is just a random generated guid?

I noticed the id referring the blog from @glombek is without hyphen and the logo/avatar is the following:
https://2.gravatar.com/avatar/6e03aef14c3e69d4e14b111b10d480a70ecc5a60a7dd5975472a68c06f5b48e8?size=256

but the same version here - maybe preferable.
https://gravatar.com/avatar/6e03aef14c3e69d4e14b111b10d480a70ecc5a60a7dd5975472a68c06f5b48e8?size=256

### CODE REVIEW

**Comment by glombek** [comment]
Apparently I like causing havoc 😬 

I'll take @nul800sebastiaan's guidance whether he wants me to PR a tidy up of my mess of a contribution 🙈

**Comment by nul800sebastiaan** [comment]
I don't parse it as a GUID, so any identifier. As long as it's unique.

**Comment by bjarnef** [comment]
@nul800sebastiaan is there any specific area these are using of only here: https://our.umbraco.com/CommunityBlogsRss

I think there used to be an Forum section on frontpage https://our.umbraco.com/

**Comment by bjarnef** [comment]
> And it is automatically posting new posts in the `#news` Discord channel.

Thanks :)
I guess it only happen to upcoming/new blog posts which already was configured in this JSON file?

**Comment by nul800sebastiaan** [comment]
Yep, only new posts from now on (otherwise each RSS feed merge would lead to chaos in that channel).

**Pull request merged**
