### PR TITLE
Updated site URL in the home content

### PR DESCRIPTION
**Pull request by ed-parry**
Another tiny update but a valuable one to not confuse users. Ran a quick check to see if there any further mentions but can't see anything else that isn't relative.

### CODE REVIEW

**Comment by abjerner** [comment]
Btw - if you're up for the task, there may still be some occurrences here and there:

https://github.com/umbraco/OurUmbraco/search?q=our.umbraco.org&unscoped_q=our.umbraco.org

Not all of them are relevant to fix, but some are. And some occurrences are probably in legacy code that isn't used anymore.

**Comment by ed-parry** [comment]
Thanks @abjerner - added in a few more. Searched through `cshtml` and `cs` files for any that appear in text, or more crucial links to save on the redirect. Introducing a constant could make sense, especially if it's possible/likely that further changes could be made.

I have another question for @nul800sebastiaan - email addresses used in the `from` fields, sometimes robot@umbraco.org - are these save to switch to .com, or is the email server still using .org? Or are these just placeholders anyway?

**Comment by ed-parry** [comment]
@abjerner @nul800sebastiaan Merged in the latest to resolve conflicts in case this one is still of value :)

**Comment by nul800sebastiaan** [comment]
Awesome, thanks @ed-parry ! I'll deploy this soon!

**Pull request merged**
