### PR TITLE
Add my blog to the list

### PR DESCRIPTION
**Pull request by rasolo**

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Thanks @rasolo! 

Congrats on your first contribution to Our Umbraco as well, I've added a new contributor badge to your profile https://our.umbraco.com/members/id:278134/ 🏅

**Comment by rasolo** [comment]
Thanks Sebastian!

**Comment by nul800sebastiaan** [comment]
Hey there @rasolo - I've deployed this but unfortunately your feed is not working, seems like it's missing a `<channel>` node. Can you update the rss feed on your end?

**Comment by rasolo** [comment]
Hey @nul800sebastiaan, I have updated the feed with a <channel> node now. I have created a new blog post but it does not show up here https://our.umbraco.com/community/blog-posts/, But it says it is 25th october for the latest blog post at Umbraco and locally for me and the feed it is 24th of October so any posts I make now might not show up then?

**Comment by nul800sebastiaan** [comment]
@rasolo The cache only updates once an hour, which just happened, so you see your posts now! 👍

**Comment by rasolo** [comment]
@nul800sebastiaan Haha fantastic, really cool!

**Comment by nul800sebastiaan** [comment]
Hi there @rasolo,

First of all: **A big #H5YR** for contributing to Umbraco during Hacktoberfest! We are very thankful for the huge amount of PRs submitted, and all the amazing work you've been doing 🥇 

We have had another record breaking amount of PR's in both the CMS, Documentation, and other smaller public repositories. You can read all about the numbers in the [Umbraco Hacktoberfest round-up blog post](https://umbraco.com/blog/pr-team-update-november-2019-hacktoberfest-round-up/).

Due to the amazing work you and others in the community have been doing, we've had a bit of a hard time keeping up. 😅 While all of the PRs for Hacktoberfest might not have been merged yet, you still qualify for receiving some Umbraco swag, congratulations! 🎉 

In the spirit of Hacktoberfest we've prepared some **exclusive Umbraco swag** for all our contributors - _including you_! 

[Receive your swag!](https://docs.google.com/forms/d/e/1FAIpQLSc-K97Zl5k86cVebKWWqieLM4Fm_jCMGVdbQdYnq4IUJ7EvZg/viewform) :point_left: Please follow this link to fill out and submit the form, **before December 19th 2019**.

Following this date we'll be sending out all the swag, which also means that it might not reach your doorstep before February, so please bear with us and be patient :pray:

The only thing left to say is **thank you so much for participating in Hacktoberfest**! We really appreciate the help!

Kind regards,
The Umbraco PR Team & The Documentation Curators

**Comment by rasolo** [comment]
Hi @nul800sebastiaan ,

Thanks a lot! I have submitted the form,

Kind regards,
Rasmus

**Pull request merged**
