### PR TITLE
Add too orangey for crows to the list of community umbraco blogs

### PR DESCRIPTION
**Pull request by marcemarc**
it's no longer possible to find your member id from the 'view my public profile' link?

### CODE REVIEW

**Comment by abjerner** [comment]
Hi Marc,

Unfortunately Our doesn't know to look for your Atom dates (eg. like `<a10:updated>2020-09-25T12:28:27+01:00</a10:updated>`). Could you add RFC 822 based `<pubDate>` elements as well? Otherwise the RSS parser at Our will ignore your posts 😢

**Comment by marcemarc** [comment]
@abjerner that's showing it's age...

is this any better? http://tooorangey.co.uk/rssfeed

regards

Marc

**Comment by abjerner** [comment]
@marcemarc I think so, yes 👍

**Comment by nul800sebastiaan** [comment]
Thanks @marcemarc - your blog posts will appear on the site soon!

**Comment by marcemarc** [comment]
thanks @nul800sebastiaan ! - I'm taking 'this counts' towards hacktoberfest ...

**Comment by nul800sebastiaan** [comment]
Alas! Only PRs submitted in October count! 😅

**Comment by marcemarc** [comment]
noooooooooooooooooooooooooooooooooooooooooooooooooooooo!

**Pull request merged**
