### PR TITLE
Add Moriyama blog

### PR DESCRIPTION
**Pull request by darrenferguson**
Add Moriyama blog to community blogs

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
@darrenferguson Thanks! Unfortunately, we currently can't parse "Tue, 12 Mar 2019 12:17:36 EST" - instead of `EST` we're expecting a UTC offset (in your case `+00:00`). Any chance you can update your RSS feed to use that instead?

**Comment by abjerner** [comment]
@nul800sebastiaan I may have a fix for that. IIRC the `EST` is technically valid, but .NET fails to parse it.

**Comment by abjerner** [comment]
Our Umbraco already has a dependency on my `Skybrud.Essentials`, so using this method for parsing the date should work:

https://github.com/skybrud/Skybrud.Essentials/blob/v1.1.5/src/Skybrud.Essentials/Time/TimeUtils.Rfc822.cs#L54

I will look into creating a PR for the current RSS parsing logic 😉

**Comment by darrenferguson** [comment]
@nul800sebastiaan fixed!

**Comment by nul800sebastiaan** [comment]
@abjerner Ha! Ironically, we do use your lib.. but then we parse it as a datetime offset.. ;)

image

**Comment by nul800sebastiaan** [comment]
@darrenferguson cool, works now! 👍

**Comment by abjerner** [comment]
@nul800sebastiaan sure that is the code that fail? `Rfc822ToDateTimeOffset` works fine with `Tue, 12 Mar 2019 12:17:36 EST` when I call it directly.

On the other hand, the `ParseRfc822DateTime` method in the class below doesn't use my helper method:

https://github.com/umbraco/OurUmbraco/blob/master/OurUmbraco/Community/BlogPosts/BlogRssUtils.cs

**Comment by nul800sebastiaan** [comment]
@abjerner `DateTimeOffset.TryParse` is what fails there since the `publishDate` still contains `EST`.

**Comment by abjerner** [comment]
@nul800sebastiaan a missing return state could have something to do with it 😮 

PR is here: https://github.com/umbraco/OurUmbraco/pull/407

**Pull request merged**
