### PR TITLE
Email template borrowed from Umbraco source

### PR DESCRIPTION
**Pull request by mzajkowski**
We've found that e-mails don't have any templates applied. So.. we borrowed template (markup) from Umbraco source code and applied it to the existing email being sent after the registration.

The content definitely needs to be updated, but this PR is just a beginning...

### CODE REVIEW

**Comment by abjerner** [comment]
Hi Marcin,

I just tried giving this a spin, and the new email template looks awesome 👍 

I did however spot that the icon doesn't work in GMail, and presumably some other email agents. Apparently this is because the icon is a SVG (opposed to the one in Umbraco, which is a PNG). The attached PNG is the logo (measuring 32x32 pixels), which should have broader support.

logo_email

<hr />

You mention that your PR is just the beginning, so I have some suggestions going forward. As there are other types of mails being sent from, we should probably have a look at these as well.

To re-use as much of the email template as possible, it might be more ideal to use partial views instead of C# constants.

With partial views, we can have a master view with most of the template/HTML, and then individual partial views for each type of email. Sorta like the snippets below:

`Master.cshtml`:

```
<html>
<head>
    <meta name='viewport' content='width=device-width'>
    <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'>
</head>
                    
<body style='font-family: sans-serif; -webkit-font-smoothing: antialiased; font-size: 14px; color: #392F54; line-height: 22px; -ms-text-size-adjust: 100%; -webkit-text-size-adjust: 100%; background: #1d1333; margin: 0; padding: 0;' bgcolor='#1d1333'>
<style type='text/css'>
    @@media only screen and (max-width: 620px) {
        table[class=body] h1 {
            font-size: 28px !important;
            margin-bottom: 10px !important;
        }
        table[class=body] .wrapper {
            padding: 32px !important;
        }
        table[class=body] .article {
            padding: 32px !important;
        }
        table[class=body] .content {
            padding: 24px !important;
        }
        table[class=body] .container {
            padding: 0 !important;
            width: 100% !important;
        }
        table[class=body] .main {
            border-left-width: 0 !important;
            border-radius: 0 !important;
            border-right-width: 0 !important;
        }
        table[class=body] .btn table {
            width: 100% !important;
        }
        table[class=body] .btn a {
            width: 100% !important;
        }
        table[class=body] .img-responsive {
            height: auto !important;
            max-width: 100% !important;
            width: auto !important;
        }
    }
                            
    .btn-primary table td:hover {
        background-color: #34495e !important;
    }
                            
    .btn-primary a:hover {
        background-color: #34495e !important;
        border-color: #34495e !important;
    }
                            
    .btn a:visited {
        color: #FFFFFF;
    }
</style>
<table border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #1d1333;' bgcolor='#1d1333'>
    <tr>
        <td style='font-family: sans-serif; font-size: 14px; vertical-align: top; padding: 24px;' valign='top'>
            <table style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                <tr>
                    <td background='https://our.umbraco.org/assets/images/logo_email.png' bgcolor='#1d1333' width='30' height='30' valign='top' style='font-family: sans-serif; font-size: 14px; vertical-align: top;'>
                        <!--[if gte mso 9]> <v:rect xmlns:v='urn:schemas-microsoft-com:vml' fill='true' stroke='false' style='width:32px;height:32px;'> <v:fill type='tile' src='https://our.umbraco.org/assets/images/logo_email.png' color='#1d1333' /> <v:textbox inset='0,0,0,0'> <![endif]-->
                        <div> </div>
                        <!--[if gte mso 9]> </v:textbox> </v:rect> <![endif]-->
                    </td>
                    <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'></td>
                </tr>
            </table>
        </td>
    </tr>
</table>
<table border='0' cellpadding='0' cellspacing='0' class='body' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; background: #1d1333;' bgcolor='#1d1333'>
    <tr>
        <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'> </td>
        <td class='container' style='font-family: sans-serif; font-size: 14px; vertical-align: top; display: block; max-width: 560px; width: 560px; margin: 0 auto; padding: 10px;' valign='top'>
            <div class='content' style='box-sizing: border-box; display: block; max-width: 560px; margin: 0 auto; padding: 10px;'>
                <br>
                <table class='main' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%; border-radius: 3px; background: #FFFFFF;' bgcolor='#FFFFFF'>
                    <tr>
                        <td class='wrapper' style='font-family: sans-serif; font-size: 14px; vertical-align: top; box-sizing: border-box; padding: 50px;' valign='top'>
                            <table border='0' cellpadding='0' cellspacing='0' style='border-collapse: separate; mso-table-lspace: 0pt; mso-table-rspace: 0pt; width: 100%;'>
                                <tr>
                                    <td style='line-height: 24px; font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'>
                                        @RenderBody()
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                <br>
                <br>
                <br>
            </div>
        </td>
        <td style='font-family: sans-serif; font-size: 14px; vertical-align: top;' valign='top'> </td>
    </tr>
</table>
</body>
</html>
```

`SendActivationMail.cshtml`:

```
@inherits UmbracoViewPage<OurUmbraco.Forum.Library.Utils.SendActivationMailModel>
    
@{
    Layout = "Master.cshtml";
}
    
Hi @Model.Name,<br />
<br />
Thanks for signing up for the Umbraco community site. In order to be able to log in please click on the link below to activate your account:<br />
<a href="@Model.ActivationUrl">@Model.ActivationUrl</a><br />
<br />
Best regards,<br />
The Umbraco Community robot.
```

The implementation for the `SendActivationMailModel` class used for the model could look like:

```C#
        public class SendActivationMailModel
        {
            
            public IMember Member { get; }

            public string Id { get; }

            public string Name { get; }

            public string ActivationUrl => "https://our.umbraco.org/member/activate/?id=" + Id;

            public SendActivationMailModel(IMember member)
            {
                Member = member;
                Id = member.ProviderUserKey + "";
                Name = member.Name;
            }

        }
```

The `RenderPartial` method as shown below can be used to render partial views - even from static contexts like the `SendActivationMail` utility method:

```C#
        class WebFormController : Controller { }

        public static HtmlString RenderPartial(string partialName, object model)
        {

            // Get a wrapper for the legacy WebForm context
            HttpContextWrapper context = new HttpContextWrapper(HttpContext.Current);

            // Create a mock route that points to the empty controller
            RouteData route = new RouteData();
            route.Values.Add("controller", "WebFormController");

            // Create a controller context for the route and http context
            ControllerContext ctx = new ControllerContext(new RequestContext(context, route), new WebFormController());


            if (partialName.StartsWith("Partials/")) partialName = "~/Views/" + partialName;
            if (!partialName.EndsWith(".cshtml")) partialName += ".cshtml";

            // Find the partial view using the view engine
            ViewEngineResult result = ViewEngines.Engines.FindPartialView(ctx, partialName);
            if (result == null || result.View == null) throw new Exception("Partial view \"" + partialName + "\" not found.");

            // Render the partial view to a StringBuilder
            StringBuilder sb = new StringBuilder();
            using (StringWriter writer = new StringWriter(sb))
            {

                // Create a view context and assign the model
                ViewContext vctx = new ViewContext(ctx, result.View, new ViewDataDictionary { Model = model }, new TempDataDictionary(), writer);

                // Render the partial view
                result.View.Render(vctx, writer);

            }

            return new HtmlString(sb.ToString());

        }
```

Feel free to use the code above to update your PR. Otherwise I might have a look at it once this PR is merged ;)

**Comment by mzajkowski** [comment]
Hi Anders,

That's a great feedback. Thanks for your tests on the various clients as
well.

We've been thinking and discussing the idea of making the base of the email
to be reusable and I really like your suggestion of converting them into
partials. Definitely it'll make them more flexible in terms of possible
future changes.

I'll apply those suggestions to this PR and would be more than happy to let
you re-test it then.

**Comment by mzajkowski** [comment]
@abjerner I've included your suggestions with some namings changes. Please take a look. I'm still not sure about the location of EmailUtils helper methods, but I think it might land here for now.

**Comment by nul800sebastiaan** [comment]
Whoa, I just tried adding 1 commit, but I guess it just took all of the merge commits from master too. Anyway.. ;-)

I'll merge soon, just doing some last testing.

**Comment by nul800sebastiaan** [comment]
Thanks @mzajkowski and @abjerner - this seems to work great.. I'll deploy it soon and see how it goes on live 😉 🙈

**Pull request merged**
