### PR TITLE
Added a "Release Compare" section to allow you to compare the changes…

### PR DESCRIPTION
**Pull request by readingdancer**
… between two versions.

You will need to add a "Release Compare" document type and allow it to be nested under the "Release Landing" page, when you create the content page it should be called " Compare "

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Added a migration to create the template, document type, content item and macro: https://github.com/umbraco/OurUmbraco/commit/b72949404795877624047a65bab5d7122d1a1fb7

**Comment by nul800sebastiaan** [comment]
Whoop, all deployed! https://our.umbraco.org/contribute/releases/compare/

**Comment by readingdancer** [comment]
Awesome news :) I am on a train and just tried it on my mobile, I will give it a bit of mobile CSS love and do a new pull request shortly!

**Comment by readingdancer** [comment]
I have just submitted a second pull request that cleans up the layout on mobile.

https://github.com/umbraco/OurUmbraco/pull/91

**Pull request merged**
