### PR TITLE
OUR-387 Solved "green color" not showing on startpage of Our

### PR DESCRIPTION
**Pull request by Adolfi**
http://issues.umbraco.org/issue/OUR-387

Added the "solved" class on the latestactivity forum-threads.

For some reasons, i did´nt get the /assets/css/style.min.css when i
cloned the repository, and i could´nt find it in
https://github.com/umbraco/OurUmbraco/tree/master/OurUmbraco.Site
either.

This css needs to be added to style.min.css for the threads to be green:

.forum .forum-thread.solved {
background: rgba(163, 219, 120, 0.23) none repeat scroll 0 0;
border: 2px solid rgba(163, 219, 120, 0.66);
}

### CODE REVIEW

**Comment by nul800sebastiaan** [comment]
Cool, thanks! I'll deploy later this week, have a few more things to put in!

**Comment by Adolfi** [comment]
Awsome, thanks! Been bugging me for a while now and then i found your 24days article (http://24days.in/umbraco/2014/your-first-pull-request/) from 2014 and i literlly followed it step by step. Great article!!
I see how one could get addicted! :)

**Comment by Adolfi** [comment]
Btw, does one get any Our Awsomeness for these kind of small contributes? Karma / Badge? Or is that just for core changes?

**Comment by nul800sebastiaan** [comment]
Haha, sure thing, you get a contributor badge! https://our.umbraco.org/member/124117

**Comment by nul800sebastiaan** [comment]
This is now deployed, sadly there's no solved posts on the home page at the moment, so we can't see it yet! :-) Thanks again!

**Comment by Adolfi** [comment]
I can see that solved threads get the class “solved” on the home page, but they don’t get the green styling. Did you update the css I commented?

 

.forum .forum-thread.solved {

background: rgba(163, 219, 120, 0.23) none repeat scroll 0 0;

border: 2px solid rgba(163, 219, 120, 0.66);

}

 

When I import this css in my browser live editor (style.min.css) it looks great!

 

Awesome, thanks for the badge!! :)

__________________________________ 

Dennis Adolfi
Systemutvecklare
 <mailto:dennis@webmind.se> dennis@webmind.se 

 <http://www.webmind.se/> 

Sten Sturegatan 40 | 412 52 Göteborg | Vxl: 031 - 18 70 80 |  <http://www.webmind.se/> www.webmind.se 

 

Från: Sebastiaan Janssen [mailto:notifications@github.com] 
Skickat: den 13 april 2016 18:11
Till: umbraco/OurUmbraco <OurUmbraco@noreply.github.com>
Kopia: Dennis Adolfi <dennis@webmind.se>
Ämne: Re: [umbraco/OurUmbraco] OUR-387 Solved "green color" not showing on startpage of Our (#83)

 

This is now deployed, sadly there's no solved posts on the home page at the moment, so we can't see it yet! :-) Thanks again!

**Comment by nul800sebastiaan** [comment]
Ah yes, that's better!
image

**Comment by Adolfi** [comment]
Great!! Noticed it this morning, looks really nice.

Have a great day! :)

 

__________________________________ 

Dennis Adolfi
Systemutvecklare
dennis@webmind.se <mailto:dennis@webmind.se>  

 <http://www.webmind.se/> 

Sten Sturegatan 40 | 412 52 Göteborg | Vxl: 031 - 18 70 80 | www.webmind.se <http://www.webmind.se/>  

 

Från: Sebastiaan Janssen [mailto:notifications@github.com] 
Skickat: den 14 april 2016 18:17
Till: umbraco/OurUmbraco <OurUmbraco@noreply.github.com>
Kopia: Dennis Adolfi <dennis@webmind.se>
Ämne: Re: [umbraco/OurUmbraco] OUR-387 Solved "green color" not showing on startpage of Our (#83)

 

Ah yes, that's better!
 <https://cloud.githubusercontent.com/assets/304656/14535216/1349dcf6-026d-11e6-86c5-c1f242550cc0.png>

**Pull request merged**
